name: Azure Static Web Apps CI/CD

on:
  push:

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy SWA
    environment: msdn
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: azure/login@v1
        id: login
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Infrastructure
        id: infradeploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.ARM_RESOURCE_GROUP }}
          template: ./env/azuredeploy.bicep
          deploymentName: 'deploy-${{ env.GITHUB_RUN_ID }}'
          failOnStdErr: false
          additionalArguments: '--verbose'

      - name: Build And Deploy SWA
        id: swabuilddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ARM_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######